'use client'

import { useEffect } from 'react'
import { driver } from 'driver.js'
import 'driver.js/dist/driver.css'
import { BookOpen } from 'lucide-react'

const TOUR_KEY = 'polaris-tour-seen-v3'

const steps = [
  {
    popover: {
      title: 'Meet Polaris',
      description:
        '<img src="/agent-hero.png" alt="Polaris AI Agent" class="tour-hero-img" />' +
        '<ul class="tour-points">' +
        '<li>Wakes up at 5am every morning</li>' +
        '<li>Scans cold storage via computer vision</li>' +
        '<li>Flags expiring items and low stock</li>' +
        '<li>Scrapes live competitor prices</li>' +
        '<li>Delivers a full report straight to your inbox</li>' +
        '</ul>' +
        '<div class="tour-email-mock">' +
        '<div class="tour-em-head">' +
        '<span class="tour-em-from">From: Polaris Agent</span>' +
        '<span class="tour-em-subj">Daily Report — 3 items need attention</span>' +
        '</div>' +
        '<div class="tour-em-body">' +
        '<div class="tour-em-row"><span class="tour-em-name"><i class="tour-dot tour-dot-red"></i>Atlantic Salmon</span><span class="tour-em-tag tour-em-red">Expires in 2 days</span></div>' +
        '<div class="tour-em-row"><span class="tour-em-name"><i class="tour-dot tour-dot-yellow"></i>Tiger Prawns</span><span class="tour-em-tag tour-em-yellow">Reorder 50 kg at $8.40</span></div>' +
        '<div class="tour-em-row"><span class="tour-em-name"><i class="tour-dot tour-dot-blue"></i>Barramundi</span><span class="tour-em-tag tour-em-blue">Bidvest $0.80/kg cheaper</span></div>' +
        '</div>' +
        '<div class="tour-em-foot">' +
        '<a href="/runs" class="tour-logs-link" onclick="localStorage.setItem(\'polaris-tour-seen-v3\',\'1\')">View Agent Logs →</a>' +
        '</div>' +
        '</div>',
      side: 'over' as const,
      align: 'center' as const,
    },
  },
  {
    element: '#tour-scanner',
    popover: {
      title: 'Camera Scanner',
      description:
        '<img src="/scanner-demo.jpg" alt="YOLOv8 live detection in cold storage" class="tour-scanner-img" />' +
        'Point any phone at a storage zone. YOLOv8 runs directly in the browser, identifying and counting items in real time. Every scan is logged and compared to the previous count.',
      side: 'right' as const,
      align: 'start' as const,
    },
  },
  {
    element: '#tour-stats',
    popover: {
      title: 'Live Inventory Snapshot',
      description: 'Four numbers updated after every agent run. Red means expiring within 7 days. Yellow means below reorder threshold. These drive every decision the agent makes.',
      side: 'bottom' as const,
      align: 'start' as const,
    },
  },
  {
    element: '#tour-run-btn',
    popover: {
      title: 'Run the Agent',
      description: 'Triggers a full agent run right now. Watch it call tools autonomously in the terminal with no fixed order. Normally scheduled at 5am every day via GitHub Actions.',
      side: 'bottom' as const,
      align: 'end' as const,
    },
  },
  {
    element: '#tour-observability',
    popover: {
      title: 'Agent Observability',
      description: 'Every tool called across the last 7 runs, with counts and error rates. The LLM decides what to call and when. Nothing is hardcoded.',
      side: 'top' as const,
      align: 'start' as const,
    },
  },
  {
    element: '#tour-alerts',
    popover: {
      title: 'Critical Alerts',
      description: 'Items the agent flagged on its own. No rules written. The AI reads your inventory and decides what needs urgent attention.',
      side: 'top' as const,
      align: 'end' as const,
    },
  },
  {
    element: '#tour-nav-inventory',
    popover: {
      title: 'Inventory',
      description: 'Your full stock table. Every product with current quantity, expiry date, location, and colour-coded risk level. Filter by category or sort by days to expiry.',
      side: 'right' as const,
      align: 'start' as const,
    },
  },
  {
    element: '#tour-nav-logs',
    popover: {
      title: 'Agent Logs',
      description: 'A complete trace of every tool the agent called in each run. See exactly what it checked, what it found, and what it decided to do next.',
      side: 'right' as const,
      align: 'start' as const,
    },
  },
  {
    element: '#tour-nav-decisions',
    popover: {
      title: 'Decisions',
      description: 'Purchase orders and reorder recommendations generated by the agent. Includes the suggested quantity, supplier, and live price at the time of the run.',
      side: 'right' as const,
      align: 'start' as const,
    },
  },
  {
    element: '#tour-nav-monitor',
    popover: {
      title: 'Monitor',
      description: 'Run health over time. See success and failure rates, tool call volumes, and how the agent is trending week on week.',
      side: 'right' as const,
      align: 'start' as const,
    },
  },
  {
    element: '#tour-nav-putaway',
    popover: {
      title: 'Put Away',
      description: 'Smart put-away guidance for incoming stock. The agent recommends the best storage zone based on expiry date, product type, and current zone capacity.',
      side: 'right' as const,
      align: 'start' as const,
    },
  },
  {
    element: '#tour-nav-competitors',
    popover: {
      title: 'Competitor Prices',
      description: 'Live prices scraped from PFD, Bidvest, and Harris Farm on every run. Compare your supplier costs against the market and spot where you are overpaying.',
      side: 'right' as const,
      align: 'start' as const,
    },
  },
  {
    element: '#tour-nav-memory',
    popover: {
      title: 'Agent Memory',
      description: 'What Polaris has learned across every run. The agent writes observations like price trends and stock patterns here and reads them back on the next run to make smarter decisions.',
      side: 'right' as const,
      align: 'start' as const,
    },
  },
  {
    element: '#tour-sidebar',
    popover: {
      title: 'You are all set',
      description: 'Hit <strong style="color:#58a6ff">Run Agent</strong> on the dashboard to trigger a live run now and watch it make decisions in real time. Or check back tomorrow morning after the 5am scheduled run. Everything updates automatically.',
      side: 'right' as const,
      align: 'start' as const,
    },
  },
]

function startTour() {
  let driverObj: ReturnType<typeof driver>

  const injectSkip = () => {
    const footer = document.querySelector('.polaris-tour .driver-popover-footer')
    if (!footer || footer.querySelector('.polaris-skip-btn')) return
    const btn = document.createElement('button')
    btn.textContent = 'Skip tour'
    btn.className = 'polaris-skip-btn'
    btn.addEventListener('click', () => driverObj.destroy())
    footer.appendChild(btn)
  }

  driverObj = driver({
    showProgress: true,
    showButtons: ['next', 'previous', 'close'],
    nextBtnText: 'Next →',
    prevBtnText: '← Back',
    doneBtnText: 'Done',
    progressText: '{{current}} of {{total}}',
    overlayColor: '#000',
    overlayOpacity: 0.72,
    stagePadding: 6,
    stageRadius: 8,
    smoothScroll: true,
    animate: true,
    allowClose: true,
    allowKeyboardControl: true,
    popoverClass: 'polaris-tour',
    steps,
    onHighlighted: injectSkip,
    onDestroyed: () => {
      localStorage.setItem(TOUR_KEY, '1')
    },
  })
  driverObj.drive()
}

export function DemoTour() {
  useEffect(() => {
    const seen = localStorage.getItem(TOUR_KEY)
    if (!seen) {
      const t = setTimeout(startTour, 900)
      return () => clearTimeout(t)
    }
  }, [])

  return (
    <button
      onClick={startTour}
      className="fixed bottom-6 right-6 z-40 flex items-center gap-2 px-3.5 py-2 bg-[#1f6feb] hover:bg-[#388bfd] text-white text-[12px] font-medium rounded-full shadow-lg transition-colors select-none"
    >
      <BookOpen size={13} />
      Take a tour
    </button>
  )
}
