import { Resend } from 'resend'
import * as dotenv from 'dotenv'
import * as path from 'path'

dotenv.config({ path: path.resolve(process.cwd(), '.env.local') })

const SITE_API = 'https://www.tasmanstarseafoodmarket.com.au/api/products'
const SITE_URL = 'https://www.tasmanstarseafoodmarket.com.au/online-ordering'

interface SiteProduct {
  id: string
  name: string
  slug: string
  price: string
  unit: string
  stockQuantity: number
  isFeatured: boolean
  isTodaysSpecial: boolean
  category: { name: string; slug: string }
}

async function fetchSashimiProducts(): Promise<SiteProduct[]> {
  const res = await fetch(`${SITE_API}?category=sashimi&limit=50`, {
    headers: { 'User-Agent': 'Mozilla/5.0 Polaris-Agent/1.0' },
  })
  if (!res.ok) throw new Error(`API error: ${res.status}`)
  const data = await res.json()
  return data.products as SiteProduct[]
}

function buildEmail(products: SiteProduct[]): string {
  const rows = products.map(p => {
    const badges = [
      p.isTodaysSpecial ? '<span style="background:#e74c3c;color:#fff;padding:2px 6px;border-radius:3px;font-size:10px;margin-left:4px;">TODAY\'S SPECIAL</span>' : '',
      p.isFeatured ? '<span style="background:#f39c12;color:#fff;padding:2px 6px;border-radius:3px;font-size:10px;margin-left:4px;">FEATURED</span>' : '',
    ].join('')

    return `
    <tr>
      <td style="padding:10px 12px;border-bottom:1px solid #2a2a2a;">
        ${p.name}${badges}
      </td>
      <td style="padding:10px 12px;border-bottom:1px solid #2a2a2a;color:#27ae60;font-weight:700;font-size:15px;">
        $${parseFloat(p.price).toFixed(2)}
      </td>
      <td style="padding:10px 12px;border-bottom:1px solid #2a2a2a;color:#888;font-size:12px;">
        per ${p.unit.toLowerCase()}
      </td>
      <td style="padding:10px 12px;border-bottom:1px solid #2a2a2a;color:${p.stockQuantity < 15 ? '#e74c3c' : '#888'};font-size:12px;">
        ${p.stockQuantity} in stock
      </td>
    </tr>`
  }).join('')

  const dateStr = new Date().toLocaleString('en-AU', { timeZone: 'Australia/Sydney' })

  return `<!DOCTYPE html>
<html>
<head><meta charset="UTF-8"></head>
<body style="background:#0d1117;color:#e8e8e8;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',sans-serif;margin:0;padding:20px;">
  <div style="max-width:680px;margin:0 auto;">

    <div style="background:#1a1a2e;border-radius:12px;padding:24px;margin-bottom:20px;border-left:4px solid #4f8ef7;">
      <div style="font-size:11px;color:#4f8ef7;letter-spacing:2px;text-transform:uppercase;margin-bottom:8px;">Polaris Agent — Website Price Check</div>
      <div style="font-size:22px;font-weight:700;margin-bottom:4px;">Sushi &amp; Sashimi Live Prices</div>
      <div style="font-size:13px;color:#888;">${dateStr} AEST</div>
      <div style="margin-top:10px;">
        <a href="${SITE_URL}" style="color:#4f8ef7;font-size:12px;">View on tasmanstarseafoodmarket.com.au →</a>
      </div>
    </div>

    <div style="background:#001a0d;border-radius:8px;padding:20px;border:1px solid #0a3a20;">
      <div style="font-size:12px;color:#27ae60;text-transform:uppercase;letter-spacing:1px;margin-bottom:16px;font-weight:600;">
        ${products.length} product${products.length !== 1 ? 's' : ''} — Sashimi category
      </div>
      <table width="100%" cellpadding="0" cellspacing="0" style="font-size:13px;">
        <thead>
          <tr style="color:#888;font-size:11px;text-transform:uppercase;letter-spacing:1px;">
            <th style="padding:6px 12px;text-align:left;">Product</th>
            <th style="padding:6px 12px;text-align:left;">Price (AUD)</th>
            <th style="padding:6px 12px;text-align:left;">Unit</th>
            <th style="padding:6px 12px;text-align:left;">Stock</th>
          </tr>
        </thead>
        <tbody>${rows}</tbody>
      </table>
    </div>

    <div style="text-align:center;padding:20px;color:#444;font-size:11px;">
      Generated by Polaris — Autonomous Inventory Intelligence
    </div>
  </div>
</body>
</html>`
}

async function run() {
  console.log('Fetching sashimi products from Tasman Star website...')
  const products = await fetchSashimiProducts()
  console.log(`Found ${products.length} products:`)
  products.forEach(p => console.log(`  ${p.name} — $${p.price} / ${p.unit}`))

  const resend = new Resend(process.env.RESEND_API_KEY!)
  const html = buildEmail(products)

  const { data, error } = await resend.emails.send({
    from: process.env.RESEND_FROM!,
    to: [process.env.ADMIN_EMAIL!],
    subject: `Polaris — Sushi & Sashimi Prices · ${new Date().toLocaleDateString('en-AU')}`,
    html,
  })

  if (error) {
    console.error('Email failed:', error)
    process.exit(1)
  }

  console.log(`\nEmail sent to ${process.env.ADMIN_EMAIL}`)
  console.log(`Email ID: ${data?.id}`)
}

run().catch(err => {
  console.error('Fatal:', err)
  process.exit(1)
})
